[versions]

material = "1.11.0"
constraintlayout = "2.1.4"
recyclerview = "1.3.2"
core = "1.12.0"
appcompat = "1.6.1"
activity = "1.8.2"

android = "8.3.0"
kotlin = "1.9.22"

sdk-min = "26"
sdk-compile = "34"
sdk-target = "34"
java-target = "17"

[libraries]

material = { group = "com.google.android.material", name = "material", version.ref = "material" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }
core = { group = "androidx.core", name = "core-ktx", version.ref = "core" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
activity = { group = "androidx.activity", name = "activity-ktx", version.ref = "activity" }

[plugins]

android = { id = "com.android.application", version.ref = "android" }
kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }